# Generated by Django 5.2.8 on 2026-02-16 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_blood_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonation",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blooddonation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blooddonation",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection (e.g., disease)", null=True
            ),
        ),
        migrations.AddField(
            model_name="blooddonation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection", null=True
            ),
        ),
    ]
