# Generated by Django 5.2.8 on 2026-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_blood_system",
            "0002_blooddonation_approved_at_blooddonation_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="patient_age",
            field=models.IntegerField(
                blank=True, help_text="Patient age in years", null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="patient_gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=10,
            ),
        ),
    ]
