# Generated by Django 5.2.8 on 2026-02-26 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_blood_system",
            "0003_bloodrequest_patient_age_bloodrequest_patient_gender_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00", "9:00 AM"),
                            ("10:00", "10:00 AM"),
                            ("11:00", "11:00 AM"),
                            ("12:00", "12:00 PM"),
                            ("13:00", "1:00 PM"),
                            ("14:00", "2:00 PM"),
                            ("15:00", "3:00 PM"),
                            ("16:00", "4:00 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Hospital or donation center", max_length=200
                    ),
                ),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core_blood_system.donor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["appointment_date", "time_slot"],
            },
        ),
        migrations.CreateModel(
            name="MatchedDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.IntegerField(
                        help_text="Matching score based on compatibility, distance, etc."
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Distance from donor to hospital",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("notified", "Notified"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="matched",
                        max_length=20,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_donors",
                        to="core_blood_system.bloodrequest",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_requests",
                        to="core_blood_system.donor",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "distance_km"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("blood_request", "Blood Request"),
                            ("donation", "Donation"),
                            ("match", "Donor Match"),
                            ("system", "System"),
                            ("urgent", "Urgent Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("donor", "Donor ID"),
                            ("certificate", "Donation Certificate"),
                            ("blood_bag", "Blood Bag"),
                            ("appointment", "Appointment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique QR code string", max_length=100, unique=True
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Additional data encoded in QR", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_count", models.IntegerField(default=0)),
                ("last_scanned", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="core_blood_system.donationappointment",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="core_blood_system.blooddonation",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="core_blood_system.donor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="donationappointment",
            index=models.Index(
                fields=["appointment_date", "status"],
                name="core_blood__appoint_aa2011_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matcheddonor",
            index=models.Index(
                fields=["blood_request", "status"],
                name="core_blood__blood_r_50380a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matcheddonor",
            unique_together={("blood_request", "donor")},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="core_blood__user_id_5845fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["code"], name="core_blood__code_ad154e_idx"),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["qr_type"], name="core_blood__qr_type_2820e2_idx"
            ),
        ),
    ]
