# Generated by Django 5.2.8 on 2026-02-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_blood_system",
            "0005_emailverification_twofactorauth_usersession_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="twofactorauth",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminAuditLog",
        ),
        migrations.DeleteModel(
            name="EmailVerification",
        ),
        migrations.DeleteModel(
            name="TwoFactorAuth",
        ),
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
