# Generated by Django 5.2.8 on 2026-03-11 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_blood_system", "0006_remove_security_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodinventory",
            name="alert_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Last alert timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodinventory",
            name="critical_threshold",
            field=models.IntegerField(default=2, help_text="Critical low level"),
        ),
        migrations.AddField(
            model_name="bloodinventory",
            name="optimal_level",
            field=models.IntegerField(default=20, help_text="Optimal stock level"),
        ),
        migrations.AddField(
            model_name="donor",
            name="eligibility_notes",
            field=models.TextField(
                blank=True, help_text="Notes about eligibility status", null=True
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="is_eligible_override",
            field=models.BooleanField(
                default=False, help_text="Admin override for eligibility"
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="next_eligible_date",
            field=models.DateField(
                blank=True, help_text="Next date donor is eligible to donate", null=True
            ),
        ),
        migrations.CreateModel(
            name="DonorEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("weight", models.FloatField(help_text="Weight in kilograms")),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                (
                    "recent_illness",
                    models.BooleanField(
                        default=False, help_text="Illness within last 14 days"
                    ),
                ),
                ("current_medication", models.BooleanField(default=False)),
                ("anemia", models.BooleanField(default=False)),
                ("blood_pressure_issues", models.BooleanField(default=False)),
                ("is_eligible", models.BooleanField(default=False)),
                ("ineligibility_reasons", models.TextField(blank=True)),
                ("next_eligible_date", models.DateField(blank=True, null=True)),
                ("assessment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_assessments",
                        to="core_blood_system.donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor Eligibility",
                "verbose_name_plural": "Donor Eligibilities",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "urgent_blood_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive urgent blood need alerts via email",
                    ),
                ),
                (
                    "appointment_reminder_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive appointment reminders via email",
                    ),
                ),
                (
                    "appointment_confirmation_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive booking confirmations via email",
                    ),
                ),
                (
                    "request_status_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive request status updates via email",
                    ),
                ),
                (
                    "low_stock_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive low stock alerts via email (admin only)",
                    ),
                ),
                (
                    "urgent_blood_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Receive urgent blood need alerts via SMS",
                    ),
                ),
                (
                    "appointment_reminder_sms",
                    models.BooleanField(
                        default=True, help_text="Receive appointment reminders via SMS"
                    ),
                ),
                (
                    "appointment_confirmation_sms",
                    models.BooleanField(
                        default=False, help_text="Receive booking confirmations via SMS"
                    ),
                ),
                (
                    "request_status_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Receive request status updates via SMS",
                    ),
                ),
                (
                    "low_stock_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Receive low stock alerts via SMS (admin only)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="BloodUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("donation_date", models.DateField()),
                (
                    "expiration_date",
                    models.DateField(help_text="Typically 42 days from donation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("discarded", "Discarded"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        help_text="Unique identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "volume_ml",
                    models.IntegerField(default=450, help_text="Standard unit volume"),
                ),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_units",
                        to="core_blood_system.blooddonation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Unit",
                "verbose_name_plural": "Blood Units",
                "ordering": ["expiration_date", "donation_date"],
                "indexes": [
                    models.Index(
                        fields=["blood_type", "status"],
                        name="core_blood__blood_t_0548a8_idx",
                    ),
                    models.Index(
                        fields=["expiration_date"],
                        name="core_blood__expirat_35a49a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=50)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(help_text="Email or phone number", max_length=200),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="Twilio SID, etc.", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "notification_type"],
                        name="core_blood__user_id_e9badd_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_blood__status_a65e09_idx",
                    ),
                ],
            },
        ),
    ]
